name: quanttide_course
description: 量潮课程研发Dart SDK
version: 0.2.0-alpha.1
homepage: https://github.com/quanttide/quanttide-course-toolkit
repository: https://github.com/quanttide/quanttide-course-toolkit

environment:
  sdk: ^3.11.5

dev_dependencies:
  test: ^1.25.0
